version: '3.7'

services:
  app:
    build:
      context: .
    expose:
      - "8000"
    volumes:
      - static_data:/app/staticfiles
    environment:
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=127.0.0.1, localhost
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
